services:
  db:
    image: postgres:16.3
    restart: always
    container_name: postgresql
    volumes:
      - "${DB_PATH}:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5431:80"
    depends_on:
      - db

  web:
    image: django_work:${PROJECT_VERSION}
    container_name: django_hours_${PROJECT_VERSION}
    command: ./run.sh
    restart: always
    volumes:
      - ".:/code"
      - static:/code/staticfiles
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - DJANGO_ADMIN_URL=${DJANGO_ADMIN_URL}
    depends_on:
      - db

  nginx:
    image: nginx
    ports:
      - "8083:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/usr/share/nginx/html/static
    depends_on:
      - web

volumes:
  static:
