#!/bin/bash

# Usa la variable de entorno PROJECT_VERSION exportada antes
CONTAINER_NAME="django_lama_${PROJECT_VERSION}"

echo "Running tests inside container $CONTAINER_NAME..."

if ! docker exec "$CONTAINER_NAME" pytest; then
  echo "Tests failed, aborting push."
  exit 1
fi

exit 0