#!/bin/bash

# Uses the env variable PROJECT_VERSION 
CONTAINER_NAME="django_lama_${PROJECT_VERSION}"

echo "Running tests inside container $CONTAINER_NAME..."

if ! docker exec "$CONTAINER_NAME" pytest; then
  echo "Tests failed, aborting push."
  exit 1
fi

exit 0