# Generated by Django 5.0.6 on 2024-11-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
