# Generated by Django 5.0.7 on 2024-11-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_secondary_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
