# Generated by Django 5.0.7 on 2024-11-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_institute_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('technician', 'Technician'), ('researcher', 'Researcher'), ('associate', 'Associate'), ('engineer', 'Engineer'), ('administrator', 'Administrator')], max_length=20),
        ),
    ]
