# Generated by Django 5.0.7 on 2024-12-08 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='secondary_email',
        ),
    ]
