# Generated by Django 5.0.7 on 2024-12-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_member_secondary_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='secondary_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
