# Generated by Django 5.0.7 on 2024-12-08 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_secondary_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='secondary_email',
        ),
    ]
