# Generated by Django 5.0.7 on 2025-01-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_member_role_authordetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authordetails',
            old_name='email',
            new_name='author_email',
        ),
        migrations.RenameField(
            model_name='authordetails',
            old_name='institute_1',
            new_name='institute_1_id',
        ),
        migrations.RenameField(
            model_name='authordetails',
            old_name='institute_2',
            new_name='institute_2_id',
        ),
        migrations.RenameField(
            model_name='authordetails',
            old_name='institute_3',
            new_name='institute_3_id',
        ),
        migrations.AlterField(
            model_name='authordetails',
            name='author_first_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='authordetails',
            name='author_last_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='authordetails',
            name='long_institute_1',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='authordetails',
            name='long_institute_2',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='authordetails',
            name='long_institute_3',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='authordetails',
            name='orcid',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
