# Generated by Django 5.0.7 on 2025-01-12 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_rename_email_authordetails_author_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authordetails',
            name='author_first_name',
        ),
        migrations.RemoveField(
            model_name='authordetails',
            name='author_last_name',
        ),
        migrations.RemoveField(
            model_name='authordetails',
            name='institute_1_id',
        ),
        migrations.RemoveField(
            model_name='authordetails',
            name='institute_2_id',
        ),
        migrations.RemoveField(
            model_name='authordetails',
            name='institute_3_id',
        ),
        migrations.AddField(
            model_name='authordetails',
            name='author_name_family',
            field=models.CharField(blank=True, help_text='Family name as it appears in publications.', max_length=80),
        ),
        migrations.AddField(
            model_name='authordetails',
            name='author_name_given',
            field=models.CharField(blank=True, help_text='Given name as it appears in publications.', max_length=80),
        ),
        migrations.AddField(
            model_name='authordetails',
            name='institutes',
            field=models.ManyToManyField(blank=True, help_text='Institutes associated with this author for publications.', to='members.institute'),
        ),
        migrations.AlterField(
            model_name='authordetails',
            name='author_email',
            field=models.EmailField(blank=True, help_text='Email used for publications.', max_length=254),
        ),
        migrations.AlterField(
            model_name='authordetails',
            name='author_name',
            field=models.CharField(blank=True, help_text='Full author name as it appears in publications.', max_length=150),
        ),
        migrations.AlterField(
            model_name='authordetails',
            name='long_institute_1',
            field=models.TextField(blank=True, help_text='Long-form description of the first institute.'),
        ),
        migrations.AlterField(
            model_name='authordetails',
            name='long_institute_2',
            field=models.TextField(blank=True, help_text='Long-form description of the second institute.'),
        ),
        migrations.AlterField(
            model_name='authordetails',
            name='long_institute_3',
            field=models.TextField(blank=True, help_text='Long-form description of the third institute.'),
        ),
        migrations.AlterField(
            model_name='authordetails',
            name='member',
            field=models.OneToOneField(help_text='The member associated with this author information.', on_delete=django.db.models.deletion.CASCADE, related_name='author_details', to='members.member'),
        ),
    ]
