# Generated by Django 5.0.7 on 2025-01-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_remove_authordetails_author_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='is_lst',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='long_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='long_name',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
