# Generated by Django 5.0.7 on 2025-01-12 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_institute_is_lst_institute_long_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutes', to='members.group'),
        ),
    ]
