# Generated by Django 5.0.7 on 2025-01-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_alter_institute_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='long_name',
            field=models.CharField(max_length=100),
        ),
    ]
