# Generated by Django 5.0.7 on 2025-01-13 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_alter_institute_long_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authordetails',
            name='institutes',
        ),
        migrations.RemoveField(
            model_name='authordetails',
            name='long_institute_1',
        ),
        migrations.RemoveField(
            model_name='authordetails',
            name='long_institute_2',
        ),
        migrations.RemoveField(
            model_name='authordetails',
            name='long_institute_3',
        ),
        migrations.CreateModel(
            name='AuthorInstituteAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='The order in which the institute appears for the author.')),
                ('author_details', models.ForeignKey(help_text='The author details associated with this institute.', on_delete=django.db.models.deletion.CASCADE, related_name='institute_affiliations', to='members.authordetails')),
                ('institute', models.ForeignKey(help_text='Institute affiliated with this author.', on_delete=django.db.models.deletion.CASCADE, to='members.institute')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('author_details', 'institute')},
            },
        ),
    ]
