# Generated by Django 5.0.7 on 2025-01-19 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_remove_authordetails_institutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='long_name',
            field=models.CharField(help_text='The full name for the institute. Must be unique.', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='institute',
            name='name',
            field=models.CharField(help_text='A unique short name (abbreviation) for the institute, to be used in the app.', max_length=100, unique=True),
        ),
    ]
