# Generated by Django 5.0.6 on 2025-04-30 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_alter_institute_long_name_alter_institute_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duty',
            options={'verbose_name_plural': 'Duties'},
        ),
        migrations.AlterModelOptions(
            name='memberduty',
            options={'verbose_name_plural': 'Member Duties'},
        ),
        migrations.AddField(
            model_name='authorinstituteaffiliation',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 30, 9, 25, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
