# Generated by Django 5.0.6 on 2025-04-30 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_alter_duty_options_alter_memberduty_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authorinstituteaffiliation',
            unique_together={('author_details', 'institute', 'order', 'creation_date')},
        ),
    ]
