# Generated by Django 5.0.6 on 2025-05-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_alter_authorinstituteaffiliation_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Duty_types',
            },
        ),
    ]
