# Generated by Django 5.0.6 on 2025-05-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_duty_duty_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='maximum_members',
            field=models.IntegerField(null=True),
        ),
    ]
