# Generated by Django 5.0.6 on 2025-05-26 13:12

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_duty_maximum_members'),
    ]

    operations = [
        UnaccentExtension(),
    ]
