# Generated by Django 5.0.6 on 2025-06-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_auto_20250526_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='isCf',
            field=models.BooleanField(default=False),
        ),
    ]
