# Generated by Django 5.0.6 on 2025-06-11 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_member_iscf'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonFound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_found', to='members.member')),
            ],
        ),
    ]
