# Generated by Django 5.0.6 on 2025-06-13 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_commonfound'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='isCf',
        ),
    ]
