# Generated by Django 5.0.6 on 2025-06-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_remove_member_iscf'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='authorshipperiod',
            constraint=models.UniqueConstraint(fields=('member', 'end_date'), name='unique_member_end_date'),
        ),
    ]
