# Generated by Django 5.0.6 on 2025-06-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0027_authorshipperiod_unique_member_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorinstituteaffiliation',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='authorinstituteaffiliation',
            name='creation_date',
            field=models.DateTimeField(),
        ),
    ]
