# Generated by Django 5.0.6 on 2025-07-04 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0029_category_duty_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='members.category'),
            preserve_default=False,
        ),

        migrations.AddConstraint(
            model_name='duty',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unique_name_category'),
        ),
    ]
