# Generated by Django 5.0.6 on 2025-07-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0030_duty_unique_name_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duty',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
