# Generated by Django 5.2.11 on 2026-03-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0031_alter_duty_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigestReportState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_key', models.CharField(max_length=100, unique=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_window_end', models.DateField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='authordetails',
            options={'ordering': ['member__name'], 'verbose_name_plural': 'AuthorDetails'},
        ),
        migrations.AlterModelOptions(
            name='authorinstituteaffiliation',
            options={'ordering': ['author_details__member__name', 'order']},
        ),
        migrations.AlterModelOptions(
            name='authorshipperiod',
            options={'ordering': ['member__name']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='commonfound',
            options={'ordering': ['member__name']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='duty',
            options={'ordering': ['name'], 'verbose_name_plural': 'Duties'},
        ),
        migrations.AlterModelOptions(
            name='dutytype',
            options={'ordering': ['name'], 'verbose_name_plural': 'Duty_types'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='institute',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='memberduty',
            options={'ordering': ['member__name'], 'verbose_name_plural': 'Member Duties'},
        ),
        migrations.AlterModelOptions(
            name='membershipperiod',
            options={'ordering': ['member__name']},
        ),
    ]
